services:
  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStong_Password123#
  WebApi:
    container_name: WebApiContainer
    image: ${DOCKER_REGISTRY-}publicholidayapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - 8080:8080
      - 8081:8081
    build:
      context: ./PublicHolidayAPI
      dockerfile: Dockerfile
    depends_on:
      - SqlServerDb
